name: PR check
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.{ts,tsx,js,jsx,json}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Run Dprint
        run: |
          npm ci
          npx dprint check ${{ env.GIT_DIFF_FILTERED }}
      - name: Run Test
        run: npm run test:coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
